os: osx
osx_image:
  - xcode10
  - xcode9.2
addons:
  homebrew:
    update: true
jobs:
  include:
    - stage: php 5.6
      osx_image: xcode10
      env:
        - PHPV=5.6
        - OS=sierra
      script: ./scripts/travisbuild
    - stage: php 5.6
      osx_image: xcode9.2
      env:
        - PHPV=5.6
        - OS=high_sierra
      script: ./scripts/travisbuild
    - stage: php 7.0
      osx_image: xcode10
      env:
        - PHPV=7.0
        - OS=sierra
      script: ./scripts/travisbuild
    - stage: php 7.0
      osx_image: xcode9.2
      env:
        - PHPV=7.0
        - OS=high_sierra
      script: ./scripts/travisbuild
    - stage: php 7.1
      osx_image: xcode10
      env:
        - PHPV=7.1
        - OS=sierra
      script: ./scripts/travisbuild
    - stage: php 7.1
      osx_image: xcode9.2
      env:
        - PHPV=7.1
        - OS=high_sierra
      script: ./scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode10
      env:
          - PHPV=7.2
          - OS=sierra
      script: ./scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode9.2
      env:
        - PHPV=7.2
        - OS=high_sierra
      script: ./scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode10
      env:
        - PHPV=7.2
        - OS=sierra
      script: ./scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode9.2
      env:
        - PHPV=7.2
        - OS=high_sierra
      script: ./scripts/travisbuild