os: osx
osx_image:
  - xcode10
  - xcode9.2
  - xcode10.2
addons:
  homebrew:
    update: true
jobs:
  include:
    - stage: php 5.6
      osx_image: xcode10
      env:
        - PHPV=5.6
        - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 5.6
      osx_image: xcode9.2
      env:
        - PHPV=5.6
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 5.6
      osx_image: xcode10.2
      env:
        - PHPV=5.6
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.0
      osx_image: xcode10
      env:
        - PHPV=7.0
        - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.0
      osx_image: xcode9.2
      env:
        - PHPV=7.0
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.0
      osx_image: xcode10.2
      env:
        - PHPV=7.0
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.1
      osx_image: xcode10
      env:
        - PHPV=7.1
        - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.1
      osx_image: xcode9.2
      env:
        - PHPV=7.1
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.1
      osx_image: xcode10.2
      env:
        - PHPV=7.1
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode10
      env:
          - PHPV=7.2
          - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode9.2
      env:
        - PHPV=7.2
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.2
      osx_image: xcode10.2
      env:
        - PHPV=7.2
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.3
      osx_image: xcode10
      env:
        - PHPV=7.3
        - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.3
      osx_image: xcode9.2
      env:
        - PHPV=7.3
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.3
      osx_image: xcode10.2
      env:
        - PHPV=7.3
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.4
      osx_image: xcode10
      env:
        - PHPV=7.4
        - OS=high_sierra
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.4
      osx_image: xcode9.2
      env:
        - PHPV=7.4
        - OS=sierra
      script:
        - "travis_wait 90 sleep 1800 &"
        - bash scripts/travisbuild
    - stage: php 7.4
      osx_image: xcode10.2
      env:
        - PHPV=7.4
        - OS=mojave
      script:
        - "travis_wait 30 sleep 1800 &"
        - bash scripts/travisbuild