jobs:
  include:
    - stage: php@7.1_high_sierra
      osx_image: xcode10
      before_script:
        - brew update
      script:
        - brew install --build-bottle valet-php@7.1
        - brew bottle valet-php@7.1
        - ls -all