osx_image: xcode10.1

jobs:
  include:
    - stage: php@7.1_high_sierra
      script:
        - brew tap henkrehorst/homebrew-php
        - brew update
        - brew install curl-openssl
        - brew install --build-bottle valet-php@7.1
        - brew bottle valet-php@7.1
        - ls -all