# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

strategy:
  matrix:
    catalina:
      imageName: 'macOS-10.15'
      variables: |
        test: 'tress'

pool:
  vmImage: $(imageName)


steps:
- script: echo $TEST
  condition: eq(variables['apiCall'], true)
  displayName: ''
- script: echo do nothing
  condition: eq(variables['apiCall'], true)