# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  doThing: false

pool:
  vmImage: 'ubuntu-latest'


steps:
- script: echo I did a thing
  condition: eq('${{ parameters.doThing }}', true)
- script: echo do nothing
  condition: eq('${{ parameters.doThing }}', true)